baseURL = "/wc"
languageCode = "en-us"
title = "WebChart"
theme = "mieweb-docs"
publishDir = "public/wc"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir=false
#enableGitInfo = true

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Comprehensive documentation for WebChart healthcare software."
  author = "WebChart"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  [params.brand]
    name = 'WebChart'
    abbr = 'WC'
    code = 'wc'

[outputFormats.SearchIndex]
baseName = "search"
mediaType = "application/json"

[outputFormats.robots]
baseName = "robots"
mediaType = "text/plain"
isPlainText = true
notAlternative = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = [ "HTML", "RSS", "SearchIndex", "robots"]

[markup.goldmark.renderer]
  unsafe= true

[module]
  [[module.mounts]]
    source = "./node_modules/lunr/lunr.min.js"
    target = "assets/js/vendor/lunr.min.js"

  [[module.mounts]]
    source = "content"
    target = "content"

  [[module.mounts]]
    source = "static"
    target = "static"

[security]
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^pandoc$']
