baseURL = "/eh"
languageCode = "en-us"
title = "Enterprise Health"
theme = "mieweb-docs"
publishDir = "public/eh"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir=false
#enableGitInfo = true

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Comprehensive documentation for Enterprise Health occupational health software."
  author = "Enterprise Health"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  [params.brand]
    name = 'Enterprise Health'
    abbr = 'EH'
    code = 'eh'

[outputFormats.SearchIndex]
baseName = "search"
mediaType = "application/json"

[outputs]
  home = [ "HTML", "RSS", "SearchIndex"]

[markup.goldmark.renderer]
  unsafe= true

[module]
  [[module.mounts]]
    source = "./node_modules/lunr/lunr.min.js"
    target = "assets/js/vendor/lunr.min.js"

  [[module.mounts]]
    source = "content"
    target = "content"

  [[module.mounts]]
    source = "static"
    target = "static"

[security]
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^pandoc$']
