baseURL = "/eh"
languageCode = "en-us"
title = "Enterprise Health"
theme = "wc-eh-docs"
publishDir = "public/eh"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir=false
#enableGitInfo = true

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "MIEDocs"
  author = "Enterprise Health"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  [params.brand]
    name = 'Enterprise Health'
    abbr = 'EH'
    code = 'eh' 

[outputFormats.SearchIndex]
baseName = "search"
mediaType = "application/json"

[outputs]
  home = [ "HTML", "RSS", "SearchIndex"]

[markup.goldmark.renderer]
  unsafe= true

[module]    
  [[module.mounts]]
    source = "./node_modules/@fortawesome/fontawesome-free/scss"
    target = "assets/scss/fontawesome"

  [[module.mounts]]
    source = "./node_modules/@fortawesome/fontawesome-free/webfonts"
    target = "static/webfonts"

  [[module.mounts]]
    source = "./node_modules/bootstrap/dist/js/bootstrap.bundle.js"
    target = "assets/js/bootstrap/bootstrap.js"    

  [[module.mounts]]
    source = "./node_modules/@fortawesome/fontawesome-free/js/all.js"
    target = "assets/js/fortawesome/fontawesome.js"    

  [[module.mounts]]
    source = "./node_modules/@popperjs/core/dist/umd/popper.js"
    target = "assets/js/popper/popper.js"

  [[module.mounts]]
    source = "./node_modules/lunr/lunr.js"
    target = "assets/js/lunr/lunr.js"

  [[module.mounts]]
    source = "./node_modules/sweetalert2/dist/sweetalert2.all.js"
    target = "assets/js/sweetalert2/sweetalert2.js"

  [[module.mounts]]
    source = "./node_modules/copy-to-clipboard/index.js"
    target = "assets/js/copy-to-clipboard/copy-to-clipboard.js"

[security]
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^pandoc$']
